# druid 连接数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/member
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: dubbo-auto-configuration-provider-demo

#扫描xml包
mybatis:
  mapper-locations: /mapper/*.xml
  configuration: #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dubbo:
  application:       #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: provider

  registry:    #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
    group: qa-member

  protocol:  #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 8889

  scan:
    base-packages: com.ps.serviceImpl #服务暴露与发现消费所在的package

server:
  port: 8082
